ALTER TYPE "MissionMetric" ADD VALUE IF NOT EXISTS 'RANKED_BATTLE';
ALTER TYPE "MissionMetric" ADD VALUE IF NOT EXISTS 'CLASS_USAGE';
ALTER TYPE "MissionMetric" ADD VALUE IF NOT EXISTS 'DECK_OBJECTIVE';
